### Site Settings ###
title               : VitorNeves();
description         : >-                               # >- means to ignore newlines until "url:"
                      Olá, me chamou Vitor Neves, desenvolvedor iOS e de games.
                      Encontrei na área de desenvolvimento a possibilidade de fazer qualquer coisa onde a limitação de cada um está na sua própria mente.
                      Prezo de ajudar e acompanhar a comunidade sempre que consigo um tempo. Gosto de novos desafios, lutando para ser um profissional e pessoa melhor.


url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Vitor Neves
  image             : /photos/eu.jpeg
# behance           : your_username
# dribbble          : your_username
  email             : j.victtor.neves@hotmail.com
  facebook          : jvfneves
  github            : VitorNevess
# gitlab            : your_username
  instagram         : vitor_nevess_
  linkedin          : vitorneves0
  medium            : j.victtor.neves
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 10040440
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
# paginate: 6
# paginate_path: "/articles/page-:num/"


# ### Posts Permalink ###
# permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock